### ISSUE TITLE
Gallery text should come from cloudinary

### ISSUE THREAD

**Issue by extremobemo** [extremobemo/clover#18]
A text file with some standard format should contain all the text needed for the shoot details. Some shoot details will have supplemental photos for branding, so maybe consider a subfolder "details" or something to hold all this.

**Comment by jerwin21** [comment]
@extremobemo Are we still doing gallery text?

**Comment by extremobemo** [comment]
Yea, but its different now. The text will live in the bottom footer on the gallery page rather than to the left of the images
