### ISSUE TITLE
Footer position adjustment lags when safari nav resizes

### ISSUE THREAD

**Issue by jerwin21** [extremobemo/clover#30]
https://github.com/user-attachments/assets/be70abf8-e0ac-4b06-8409-8d1776c4bfe8

**Comment by extremobemo** [comment]
I think this may be a non issue once we get the scrolling behind the modal fixed, since the resize only happens because the back content is scrolling

**Comment by extremobemo** [comment]
Bruh I just updated to iOS 18 and now this doesn't happen anymore
